apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.com/WhiteMuush/simplon-azure-k8s-gitops.git
    targetRevision: main
    path: manifests/database
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates/0/status
        - /spec/volumeClaimTemplates/0/spec/volumeMode
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
